//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnABot
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeviceDetails
    {
        public int DeviceId { get; set; }
        public string DeviceType { get; set; }
        public Nullable<int> DeviceCount { get; set; }
    }
}
